#!/usr/bin/env bash

pushd `dirname $0` > /dev/null
popd > /dev/null


function exec-local {
    source ./bin/$1
}

exec-local install-utils
exec-local env-prepare
exec-local install-process
exec-local install-dependencies

