
* general
  This is my emacs configuration files, the most different with previous version
  is now I use el-get as package manager. 
  
* package manage
  Since emacs version 24, emacs has buildin *elpa* as it's default package
  system. But official repo can not contain every package either every new
  versions of a package. Not every author like to contribute his package to the
  official repo. most of them just put it on github or even his own blog.

  *el-get* support almost every kind a package source, including elpa, wiki,
  github, ftp and so on.  So el-get has more abundant package resouces.

  now you only need to configure and manage your package recipe instead of whole
  package. there is already most recipe in hand contributed by others. based on
  package recipes, maintainance and update became more easier.

  el-get also support customized initial script.

  most important, el-get is vert  activity by now. and it is the most powerfull
  packge manager as I know.
* install(osx)
  emacs that comes with osx is still 22.1.1, even you have upgrade your system to 10.9.
  it pretty old and hard to use.  why not apple just do not pre-bundled such emacs.

  for mac user those who don't want to have heavy configuration, my suggestion
  is [[http://emacsformacosx.com/][emacs for osx]]：
	 1. newer
	 2. cocoa not X11
	 3. retina 

   for mac user those want to toss of emacs, just brew install it by source code.
	 #+BEGIN_SRC bash
	 brew install emacs --cocoa
	 #+END_SRC

* configuration
** command line launch
   if you want to lanuch emacs from command line, add such command alias to your .bash_profile or .zshrc
	 #+BEGIN_SRC bash
	 alias emacs='/Applications/Emacs.app/Contents/MacOS/Emacs -nw'
	 #+END_SRC
   or add a script file */usr/bin/emacs* this is better I think, cas many third
	 party package would assume the emacs path to be '/usr/bin/'， for example
	 magit. so only terminal know how to find executable emacs but not emacs
	 itself if you only add a alias.
   	 #+BEGIN_SRC bash
	 #!/bin/bash
   /Applications/Emacs.app/Contents/MacOS/Emacs -nw
	 #+END_SRC
** daemon
*** emacsosx
    for those using emacsosxna
    #+BEGIN_SRC bash
    git clone https://github.com/ferlatte/emacs-daemon-osx.git
    cd emacs-daemon-osx
    cp org.gnu.emacs.plist ~/Library/LaunchAgents
    launchctl load ~/Library/LaunchAgents/org.gnu.emacs.plist
    make
    rm -r /Applications/emacs-client.app
    cp -r emacs-client.app /Applications
    
    #+END_SRC
*** source
    for those install from source by brew
    #+BEGIN_SRC bash
    tell application "Terminal"
     do shell script "/Applications/Emacs.app/Contents/MacOS/Emacs --daemon"
    endtell
    #+END_SRC

    add this to users login tem
** key binding
   advice for mac users:
   System preferences-> keyboard -> keyboard tab -> modifier keys(right buttom corner)

   change Caps Lock Key ----> ^ Control

* packages
  packages I use frequenctly. I will eventually add a description to the usage
  of every packge if have time.
   -  babel
   -  coffee-mode
   -  dired+
   -  haml-mode
   -  flymake
   -  js2-mode
   -  json
   -  swank-js
   -  magit
   -  git-commit-mode
   -  package
   -  rinari
   -  rspec-mode
   -  ruby-block
   -  inf-ruby
   -  ruby-compilation
   -  ruby-electric
   -  ruby-mode
   -  enh-ruby-mode
   -  ruby-test-mode
   -  ruby-tools
   -  robe-mode
   -  highlight-indentation
   -  dash
   -  rubocop
   -  simple-httpd
   -  textmate
   -  yasnippet
   -  switch-window
   -  weibo.emacs
   -  smartparens
   -  eproject
   -  etags-select
   -  ;; etags-extension
   -  slime
   -  ctags
   -  rcodetools
   -  anything
   -  ;; anything-etags
   -  emacschrome
   -  emacs-http-server 
   -  auto-complete
   -  auto-complete-css
   -  auto-complete-emacs-lisp
   -  auto-complete-extension
   -  auto-complete-etags
   -  auto-complete-clang
   -  auto-complete-yasnippet
   -  rails-el 
   -  yari
   -  zencoding-mode
   -  gnuplot-mode
   -  ;; magithub
   -  nav
   -  ;; twittering-mode
   -  rvm
   -  flymake-haml
   -  flymake-sass
   -  flymake-coffee
   -  emacs-w3m
   -  scss-mode
   -  color-theme
   -  powerline
   -  dash-at-point
   -  skewer-mode
   -  web-mode
   -  ace-jump-mode
   -  exec-path-from-shell
   -  adaptive-wrap
   -  wrap-region
   -  maxframe
   -  multi-term
   -  es-lib
   -  grizzl
   -  s
   -  project-explorer
   -  projectile
   -  pkg-info
   -  recentf-ext
   -  tabbar
   -  rainbow-mode
   -  rainbow-delimiters
   -  highlight-indentation
   -  idle-highlight-mode
   -  findr
   -  enclose
   -  drag-stuff
   -  calfw
   -  ac-js2
   -  ag
   -  popup
   -  multiple-cursors
   -  google-maps
   -  google-contacts
   -  color-theme-solarized

* org
  I mainly use org as a note tools, so have many specticular configuration to
  org, such as customize tags, default templates...

  
  
 
