* general
  This is my emacs configuration files, the most different with previous version
  is now I use el-get as package manager. 
  
* package manage
  Since emacs version 24, emacs has buildin *elpa* as it's default package
  system. But official repo can not contain every package either every new
  versions of a package. Not every author like to contribute his package to the
  official repo. most of them just put it on github or even his own blog.

  *el-get* support almost every kind a package source, including elpa, wiki,
  github, ftp and so on.  So el-get has more abundant package resouces.

  now you only need to configure and manage your package recipe instead of whole
  package. there is already most recipe in hand contributed by others. based on
  package recipes, maintainance and update became more easier.

  el-get also support customized initial script.

  most important, el-get is vert  activity by now. and it is the most powerfull
  packge manager as I know.
* install(osx)
  emacs that comes with osx is still 22.1.1, even you have upgrade your system
  to 10.9.  it pretty old and hard to use.  why not apple just do not
  pre-bundled such emacs.

  for mac users those who don't want to have heavy configuration, my suggestion
  is [[http://emacsformacosx.com/][emacs for osx]], its have advantage against others in such field:
	 1. newer
	 2. cocoa not X11
	 3. retina 

   for mac user those want to toss of emacs, just brew install it by source
   code. you can control many things through pass different compile flags.
	 #+BEGIN_SRC bash
	 brew install emacs --cocoa
	 #+END_SRC

* configuration
** command line launch
   if you want to lanuch emacs from command line, add such command alias to your
   .bash_profile or .zshrc
	 #+BEGIN_SRC bash
	 alias emacs='/Applications/Emacs.app/Contents/MacOS/Emacs -nw'
	 #+END_SRC
   or add a script file */usr/bin/emacs* this is better I think, cas many third
	 party package would assume the emacs path to be '/usr/bin/'， for example
	 magit. so only terminal know how to find executable emacs but not emacs
	 itself if you only add a alias.
   	 #+BEGIN_SRC bash
	 #!/bin/bash
   /Applications/Emacs.app/Contents/MacOS/Emacs -nw
	 #+END_SRC
** daemon
*** emacsosx
    for those using emacsosxna
    #+BEGIN_SRC bash
    git clone https://github.com/ferlatte/emacs-daemon-osx.git
    cd emacs-daemon-osx
    cp org.gnu.emacs.plist ~/Library/LaunchAgents
    launchctl load ~/Library/LaunchAgents/org.gnu.emacs.plist
    make
    rm -r /Applications/emacs-client.app
    cp -r emacs-client.app /Applications
    
    #+END_SRC
*** source
    for those install from source by brew
    #+BEGIN_SRC bash
    tell application "Terminal"
     do shell script "/Applications/Emacs.app/Contents/MacOS/Emacs --daemon"
    endtell
    #+END_SRC

    add this to users login tem
** key binding
   advice for mac users:
   System preferences-> keyboard -> keyboard tab -> modifier keys(right buttom corner)

   change Caps Lock Key ----> ^Control

* packages
  packages I use frequenctly. I will eventually add a description to the usage
  of every packge if have time.

  with * prefix is package not used currently
   
   - babel
   - coffee-mode
   - dired+
   - haml-mode
   - flymake
   - js2-mode
   - json
   - magit
   - git-commit-mode
   - package
   - rinari
   - rspec-mode
   - ruby-block
   - inf-ruby
   - ruby-compilation
   - ruby-electric
   - ruby-mode
   - enh-ruby-mode
   - ruby-test-mode
   - ruby-tools
   - robe-mode
   - highlight-indentation
      
     Did you use sublime before, this package provide the same thing like sublime guideline indentation
      
     * highlight-indentation-mode displays guidelines indentation (space indentation only).
     * highlight-indentation-current-column-mode displays guidelines for the current-point indentation (space indentation only).
    
     color configuration 
     
     * (set-face-background 'highlight-indentation-face "#e3e3d3")
     * (set-face-background 'highlight-indentation-current-column-face "#c3b3b3")

   -  dash

      A modern list api for Emacs. No 'cl required
   -  [[https://github.com/bbatsov/rubocop-emacs][rubocop]]
      
      A simple Emacs interface for [[https://github.com/bbatsov/rubocop][RuboCop]] which is a Ruby static code analyzer.
      
#+NAME: tab: rubocop usage      
| Command                              | Description                                                     | RuboCop mode binding |
|--------------------------------------+-----------------------------------------------------------------+----------------------|
| M-x rubocop-check-project            | Runs RuboCop on the entire project                              | C-c  C-r  p          |
| M-x rubocop-check-directory          | Prompts from a directory on which to run  RuboCop               | C-c  C-r  d          |
| M-x rubocop-check-current-file       | Runs    RuboCop      on  the         currently   visited  file  | C-c  C-r  f          |
| M-x rubocop-autocorrect-project      | Runs    auto-correct on  the         entire      project        | C-c  C-r  P          |
| M-x rubocop-autocorrect-directory    | Prompts for a directory on which to run auto-correct            | C-c  C-r  D          |
| M-x rubocop-autocorrect-current-file | Runs    auto-correct on  the         currently   visited  file. | C-c  C-r  F          |
   - simple-httpd
   - textmate
   - yasnippet
   - switch-window
   - weibo.emacs
   - smartparens
   - eproject
   - etags-select
   - ;; etags-extension
   - slime
   - ctags
   - rcodetools
   - anything
   - ;; anything-etags
   - emacschrome
   - emacs-http-server 
   - auto-complete
   - auto-complete-css
   - auto-complete-emacs-lisp
   - auto-complete-extension
   - auto-complete-etags
   - auto-complete-clang
   - auto-complete-yasnippet
   - rails-el 
   - yari
   - zencoding-mode
   - gnuplot-mode
   - ;; magithub
   - nav
   - ;; twittering-mode
   - rvm
   - flymake-haml
   - flymake-sass
   - flymake-coffee
   - emacs-w3m
   - scss-mode
   - color-theme
   - powerline
     
     powerline theme for emacs modeline
     
   - dash-at-point

     dash integrate for emacs to query program language api
     keybinding - C-c d

   - [[https://github.com/skeeto/skewer-mode][skewer-mode]] 
      
     live web development with Emacs
     * start
       - M-x run-skewer to attach a browser to Emacs
       - From a js2-mode buffer with skewer-mode minor mode enabled, send forms to the browser to evaluate

     * js evaluating expressions
       - C-x C-e: Evaluate the form before the point and display the result in
         the minibuffer. If given a prefix argument, insert the result into the
         current buffer.
       - C-M-x: Evaluate the top-level form around the point.
       - C-c C-k: Load the current buffer.
       - C-c C-z: Select the REPL buffer.
     * css 
       - C-x C-e: Load the declaration at the point.
       - C-M-x: Load the entire rule around the point.
       - C-c C-k: Load the current buffer as a stylesheet.
     * html
       - C-M-x: Load the HTML tag immediately around the point.

   - web-mode
   - ace-jump-mode
   - exec-path-from-shell
   - adaptive-wrap
   - [[https://github.com/rejeep/wrap-region][wrap-region]]
     
     Wrap Region is a minor mode for Emacs that wraps a region with
     punctuations.. For "tagged" markup modes, such as HTML and XML, it wraps
     with tags.
   - [[https://github.com/magnars/expand-region.el][expand-region]]
     
     Expand region increases the selected region by semantic units. 
     (global-set-key (kbd "C-=") 'er/expand-region)
     
   - * maxframe
     
     instead of buildin toogle-frame-fullscreen
   - multi-term
   - es-lib
   - grizzl
   - s
   - project-explorer
   - projectile
   - pkg-info
   - recentf-ext
   - tabbar
   - rainbow-mode
     Colorize color names in buffers
     
   - rainbow-delimitewrs
     
      highlights parentheses, brackets, and braces according to their
     depth. Each successive level is highlighted in a different color.
   - highlight-indentation
   - idle-highlight-mode
     
     buildin highlight symbol C-x w . , M-s h .
     idle-highlight-mode sets an idle timer that highlights
     all occurences in the buffer of the word under the point.
   - findr
   - enclose
   - drag-stuff
   - calfw
   - [[https://github.com/ScottyB/ac-js2a][ac-js2]] 
      
     context sensitive auto-completion for Javascript in Emacs using js2-mode's parser and Skewer-mode
      
     navigation: placing the cursor on foo, bar or baz and executing
     ac-js2-jump-to-definition or M-. will take you straight to their
     respective definitions. Executing M-, will jump you back to where you
     were.
      
     ac-js2-expand-function that will expand a function's parameters bound to
     C-c C-c. Expansion will only work if the cursor is after the function.

   - ag
   - popup
   - multiple-cursors
   - google-maps
   - google-contacts
   - color-theme-solarized

* org
  I mainly use org as a note tools, so have many specticular configuration to
  org, such as customize tags, default templates...

  
  
 
