(global-set-key (kbd "C-=") 'er/expand-region)
(global-set-key (kbd "C-c ' = =") 'er/expand-region)
(global-set-key (kbd "C-c ' = d") 'er/mark-defun)
(global-set-key (kbd "C-c ' = u") 'er/mark-url)
(global-set-key (kbd "C-c ' = w") 'er/mark-word)
(global-set-key (kbd "C-c ' = e") 'er/mark-email)
(global-set-key (kbd "C-c ' = s") 'er/mark-symbol)
(global-set-key (kbd "C-c ' = c") 'er/mark-comment)
